[platformio]
src_dir = ./
src_main = work.ino

[env:esp32dev]
board = esp32dev

board_build.filesystem = spiffs

; Wichtig: Das pioarduino-Platform-Paket verwenden!
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.12/platform-espressif32.zip

framework = arduino

; Pfad zum SimpleFOC GitHub-Repository für die absolut neueste Version
; Alternativ: askuric/Simple FOC@^2.4.0 für die letzte stable Version
lib_deps =
    bblanchon/ArduinoJson@^7.0.0

; Serielle Monitor-Geschwindigkeit
monitor_speed = 115200

; (Optional) Build-Flags, wenn nötig
build_flags =
    -Wno-missing-field-initializers
    -I src/Arduino-FOC/src
